name: K3s Deploy

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reinstall:
        description: 'Reinstall K3s'
        required: false
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.K3S_SSH_HOST }}
        username: ${{ secrets.K3S_SSH_USER }}
        key: ${{ secrets.K3S_SSH_KEY }}
        port: ${{ secrets.K3S_SSH_PORT }}
        script: |
          echo "Hello, K3s!"
          k3s=$(which k3s)
          echo $k3s
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then          
            if [ -z ${{ github.event.inputs.reinstall }} ]; then
              if [ ! -z $k3s ]; then
                sh /usr/local/bin/k3s-uninstall.sh
              fi
              curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik --write-kubeconfig-mode=644" sh
          fi
          else
            if [ -z $k3s ]; then
              curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik --write-kubeconfig-mode=644" sh
            fi
          fi