name: K3s Deploy

on:
  cron:
    - '0 */12 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

inputs:
  reinstall:
    description: 'Reinstall K3s'
    required: false
    default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install K3s
        run: |
          $k3s=$(which k3s)
          if [ -z ${{ github.event.inputs.reinstall }} ]; then
            if [ ! -z $k3s ]; then
              K3S_SSH -i ${{ secrets.K3S_SSH_KEY }} ${{ secrets.K3S_SSH_USER }}@${{ secrets.K3S_SSH_HOST }} "sh /usr/local/bin/k3s-uninstall.sh"
            fi
            K3S_SSH -i ${{ secrets.K3S_SSH_KEY }} ${{ secrets.K3S_SSH_USER }}@${{ secrets.K3S_SSH_HOST }} "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik --write-kubeconfig-mode=644" sh"
          else
            if [ -z $k3s ]; then
              K3S_SSH -i ${{ secrets.K3S_SSH_KEY }} ${{ secrets.K3S_SSH_USER }}@${{ secrets.K3S_SSH_HOST }} "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik --write-kubeconfig-mode=644" sh"
            fi
          fi