name: K3s Deploy

on:
  schedule:
    - cron: '* */12 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reinstall:
        description: 'Reinstall K3s'
        required: false
        default: false

jobs:
  k3s:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.K3S_SSH_HOST }}
        username: ${{ secrets.K3S_SSH_USER }}
        key: ${{ secrets.K3S_SSH_KEY }}
        port: ${{ secrets.K3S_SSH_PORT }}
        script: |
          echo "Hello, K3s!"
          k3s=$(which k3s)
          echo $k3s
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then          
            if [ -z ${{ github.event.inputs.reinstall }} ]; then
              if [ ! -z $k3s ]; then
                sh /usr/local/bin/k3s-uninstall.sh
              fi
              curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik --write-kubeconfig-mode=644" sh
          fi
          else
            if [ -z $k3s ]; then
              curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik --write-kubeconfig-mode=644" sh
            fi
          fi
  argocd:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1.5.0'
      with:
        release: 'loibis-argo'
        namespace: 'argocd'
        chart: 'argo-cd'
        token: '${{ github.token }}'
        repo: https://argoproj.github.io/argo-helm
        version: 7.3.11
        value-files: "argocd/values.yaml"
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'