name: K3s Deploy

on:
  schedule:
    - cron: '* */12 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      reinstall:
        description: 'Reinstall K3s'
        required: false
        default: false

jobs:
  k3s:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.K3S_SSH_HOST }}
        username: ${{ secrets.K3S_SSH_USER }}
        key: ${{ secrets.K3S_SSH_KEY }}
        port: ${{ secrets.K3S_SSH_PORT }}
        script: |
          echo "Hello, K3s!"
          k3s=$(which k3s)
          echo $k3s
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then          
            if [ -z ${{ github.event.inputs.reinstall }} ]; then
              if [ ! -z $k3s ]; then
                sh /usr/local/bin/k3s-uninstall.sh
              fi
              curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik --write-kubeconfig-mode=644" sh
          fi
          else
            if [ -z $k3s ]; then
              curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --disable traefik --write-kubeconfig-mode=644" sh
            fi
          fi
  argocd:
    needs: k3s
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Helm
      uses: azure/setup-helm@v1

    - name: Configure kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.29.6'

    - name: Authenticate with Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" > kubeconfig
        export KUBECONFIG=kubeconfig

    # 4. Helm Chart'ı Deploy Et
    - name: Deploy External Helm Chart
      run: |
        helm init
        helm repo add argo https://argoproj.github.io/argo-helm
        helm repo update
        helm upgrade --install loibis-argo argo/argo-cd \
          --namespace argocd \
          --create-namespace \
          --version 7.3.11 \
          --values ./argocd/values.yaml